// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzthkxyooupvsjbhuywl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6dGhreHlvb3VwdnNqYmh1eXdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NjQyNzMsImV4cCI6MjA2MjE0MDI3M30.K68KwzWVXNh0ZGmdcAv4Iql_1tYMUpLwU6Fy_FRy2TI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);